odom_frame: world
base_link_frame: baroness/base_link
world_frame: world

two_d_mode: false

frequency: 20

odom0: /baroness/vins_node/odometry_shifted 
odom0_config: [true, true, true,
               true, true, true,
               false, false, false,
               false, false, false,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10

imu0: /baroness/imu
imu0_config: [false, false, false,
              false, false, false,
              true, true, true,
              true, true, true,
              true, true, true]
imu0_differential: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true
